version: "3"
  
services:
  app:
      image: php:7.2-apache
      volumes:
        - .:/var/www/html
      hostname: web.local
      ports:
        - 80:80
        - 443:443
      networks:
        - back
    

networks:
  back:
    driver: bridge